name: Compatibility with pynxtools

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  python-version: 3.12

jobs:
  pynx_compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pynxtools_versions: ["latest"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install uv and set the python version to {% raw %}${{ env.python-version }}{% endraw %}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: {% raw %}${{ env.python-version }}{% endraw %}
      - name: Install pynxtools-raman
        run: |
          uv pip install ".[dev]"
          uv pip install coverage coveralls
      - name: Install nomad
        run: |
          uv pip install nomad-lab[infrastructure]@git+https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git
      - name: Install pynxtools release version {% raw %}${{ matrix.pynxtools-version }}{% endraw %}
        run: |
          if [ {% raw %}"${{ matrix.pynxtools-version }}"{% endraw %} == "latest" ]; then
            uv pip install pynxtools
          else
           uv pip install pynxtools=={% raw %}"${{ matrix.pynxtools-version }}"{% endraw %}
          fi
      - name: Run tests
        run: |
          pytest tests/.