name: Build and publish docker images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:      

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: main
  UV_VERSION: 0.9
  PYTHON_VERSION: 3.12
  NORTH_TOOL_DIR: src/{{cookiecutter.__module_name}}/nomad/north_tools/{{cookiecutter.north_tool_name}}
  TEST_DATA_DIR: tests/data/north_tools/{{cookiecutter.north_tool_name}}
  TEST_NOTEBOOKS: CommandLine.ipynb

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  build:
    name: {{cookiecutter.north_tool_name}} image
    runs-on: ubuntu-latest
    outputs:
      tags: {% raw %}${{ steps.meta.outputs.tags }}{% endraw %} # list
      labels: {% raw %}${{ steps.meta.outputs.labels }}{% endraw %} # list
    steps:
      - uses: actions/checkout@v4
        with:
          ref: {% raw %}${{ github.head_ref || github.ref_name }}{% endraw %}
          fetch-depth: 0
          show-progress: true
          submodules: true

      # Replace driver `Docker' by `Docker-container` to support cache export/import
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: {% raw %}${{ env.REGISTRY }}/${{ github.repository }}{% endraw %}
          # set latest tag for main branch and tags
          # https://github.com/docker/metadata-action?tab=readme-ov-file#image-name-and-tag-sanitization
          tags: |
            {% raw %}type=ref,event=tag
            type=ref,event=pr,prefix=pr-
            type=raw,value=main,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}{% endraw %}
          flavor: |
            latest=auto

      - name: Build and export to Jupyter image {{cookiecutter.north_tool_name}} image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: {% raw %}${{ env.NORTH_TOOL_DIR }}{% endraw %}/Dockerfile
          build-args: |
            {% raw %}IMAGE_TAG=${{ env.IMAGE_TAG }}{% endraw %}
            {% raw %}UV_VERSION=${{ env.UV_VERSION }}{% endraw %}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: {% raw %}${{ steps.meta.outputs.tags }}{% endraw %}
          labels: {% raw %}${{ steps.meta.outputs.labels }}{% endraw %}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: {{cookiecutter.north_tool_name}}-image
          path: {% raw %}${{ runner.temp }}{% endraw %}/{{cookiecutter.north_tool_name}}.tar.gz
  test_and_push_image:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    # https://docs.docker.com/build/ci/github-actions/share-image-jobs/
    steps:
      - name: Setup Repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
          # if: {% raw %}${{ github.event_name != 'pull_request' }}{% endraw %}
          uses: docker/login-action@v3
          with:
            registry: {% raw %}${{ env.REGISTRY }}{% endraw %}
            username: {% raw %}${{ github.actor }}{% endraw %}
            password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: {{cookiecutter.north_tool_name}}-image
          path: {% raw %}${{ runner.temp }}{% endraw %}
          pattern: "!*.dockerbuild" # warning at https://github.com/docker/build-push-action?tab=readme-ov-file

      # Enable this if you are building a Jupyter-based tool.
      # - name: Load and test in Jupyter container
      #   run: |
      #     {% raw %}docker load -i ${{ runner.temp }}/{{cookiecutter.north_tool_name}}.tar.gz

      #     RAW_TAGS="${{ needs.build.outputs.tags }}"
      #     echo "Raw tags: $RAW_TAGS"
      #     FIRST_TAG=$(echo "$RAW_TAGS" | tr -s '[:space:]' '\n' | grep -v '^$' | head -n 1)
      #     echo "Using tag: $FIRST_TAG"

      #     for nb in ${{ env.TEST_NOTEBOOKS }}; do
      #       echo "Running notebook: $nb"
      #       docker run \
      #         --mount type=bind,src=./${{ env.TEST_DATA_DIR }},dst="/home/jovyan/north_test" \
      #         --rm "$FIRST_TAG" \
      #         /bin/bash -c "jupyter execute \$HOME/north_test/$nb"
      #     done
      #     {% endraw %}