site_name: Documentation for {{cookiecutter.__package_name}}
site_description: |
  The documentation for the {{cookiecutter.__package_name}} plugin.
site_author: The FAIRmat authors
repo_url: https://github.com/FAIRmat-NFDI/{{cookiecutter.__package_name}}
edit_uri: ""

nav:
  - Home: index.md
  - Tutorials:
    - tutorial/installation.md
    - tutorial/contributing.md

plugins:
  - search

theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/nomad-plugin-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - search.suggest
  custom_dir: docs/theme
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji
  - mkdocs-click
  - pymdownx.extra
  - pymdownx.tabbed:
    alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false

use_directory_urls: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js